<?php

$title = 'Add new album';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?php

$album = $form->get('title');
$album->setAttribute('class', 'form-control');
$album->setAttribute('placeholder', 'Album title');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$date = $form->get('date');
$date->setAttribute('class', 'form-control');
$date->setAttribute('placeholder', 'Date');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('album', ['action' => 'add']));
$form->prepare();

?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($album) ?>
    <?= $this->formElement($album) ?>
    <?= $this->formElementErrors()->render($album, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($date) ?>
    <?= $this->formElement($date) ?>
    <?= $this->formElementErrors()->render($date, ['class' => 'help-block']) ?>
</div>

<?= $this->formSubmit($submit); ?>
<?= $this->formHidden($form->get('id')); ?>
<?= $this->form()->closeTag(); ?>